### PR TITLE
Extend ruby and test unit

### PR DESCRIPTION
**Pull request by gustavoneves12**

### CODE REVIEW

**Comment by doudou** [comment]
There's something very wrong here. Each time you make a pull request, I get the whole history

Are you rebasing ? If you do, make sure you rebase always against the current master:

```
git remote update
git rebase -i autobuild/master
```

**Comment by gustavoneves12** [comment]
I did not rebasing. I don't know what is happening. How do you create the branch? Maybe the problem is the way that I created the branch. I am creating the branch using the command line below:

```
git checkout -b branch_name
```

**Comment by doudou** [comment]
OK ... I think I got it. _I_ rebased. The problem was that, in the previous pull request, master and the branch had diverged (don't know why). Before I merged your previous PR, I rebased it on the old master and then pushed. But did not tell you.

I just updated the branch (and therefore this pull request). What you should do is (provided you have not added any commit on top of this branch):

```
git stash
git remote update
git reset --hard autobuild/extend_ruby_and_test_unit
git stash pop
```

**Comment by gustavoneves12** [comment]
I ran the command lines that you suggest to me.
In the next pull request, I will be more careful.

I guess that I need a class about the advanced git commands.

**Comment by doudou** [comment]
> I guess that I need a class about the advanced git commands.

What you need is not having me around messing the git repo without telling you ...

**Comment by doudou** [comment]
You've made a really good point ... without realizing it when you removed the UnavailableSDVersionInModel ;-) Check the two new commits I've pushed to the PR.

**Comment by gustavoneves12** [comment]
I saw your commits. 
I understand what you did. Very good!

**Comment by gustavoneves12** [comment]
Do I need to do some changes in the source code before merge?

**Comment by doudou** [comment]
Don't think so ... did the merge

**Pull request merged**
